Searches are no longer duplicated & NFC Error Checking
HackGT/Checkin-Android pull request #30
Opened 2019-01-29 22:03 UTC by Nicholas714

- Fixes searches being duplicated within search fragment
- Adds a message when NFC is unsupported / disabled on the device to prevent crashes/confusion
- Adds convenient button to take user to NFC settings if disabled
- Adds "Waiting for badge..." on track event screen

<img width="266" alt="screen shot 2019-02-08 at 5 15 03 pm" src="https://user-images.githubusercontent.com/16421258/52510535-5458ba80-2bca-11e9-8625-9d6a47d39906.png">
<img width="270" alt="screen shot 2019-02-08 at 5 17 06 pm" src="https://user-images.githubusercontent.com/16421258/52510545-5a4e9b80-2bca-11e9-97fc-12558a704bb1.png">
<img width="270" alt="screen shot 2019-02-08 at 5 15 42 pm" src="https://user-images.githubusercontent.com/16421258/52512173-7dc91480-2bd1-11e9-980f-8c2a5bba78e1.png">

closes #26 
closes #16 
closes #17

2019-02-04 00:08 UTC, evan10s requested changes
I like the direction this is going in; there are just some style/correctness things that need fixing.  I also went through and upgraded Kotlin/Gradle, removed the references to the experimental Kotlin coroutines since those are no longer experimental, and incremented the version code/number to 2.2.

2019-02-09 05:08 UTC, evan10s requested changes
Love the error messages!  A couple things:

1. "waiting for badge" should only appear on screen with the spinner
2. If it fits, consider changing NFC Device Unsupported to "Device does not support NFC"
  
Likewise, put "NFC Disabled" in sentence case to align with Android style guidelines.
3. Please add your lovely NFC errors to the screen that appears after you scan a QR code

2019-02-09 05:21 UTC, petschekr submitted a review, later dismissed

2019-02-10 06:52 UTC, evan10s approved these changes
LGTM, great work!!

2019-02-10 17:13 UTC, merged